export const userTable = "CREATE TABLE IF NOT EXISTS users(" +
    "id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
    "token VARCHAR NOT NULL DEFAULT 'Unknow'," +
    "username VARCHAR(64) UNIQUE," +
    "email VARCHAR(255) UNIQUE," +
    "password VARCHAR NOT NULL," +
    "verified BOOLEAN DEFAULT FALSE," +
    "daterelease DATE NOT NULL DEFAULT CURRENT_DATE," +
    "dateupdate DATE NOT NULL DEFAULT CURRENT_DATE)"