import express from 'express'
import cors from 'cors'

import client from './database/db.connect'
import userAuth_routes from './routes/user_auth.route.js'

// initialization
const app = express()

// middlewares
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: false }))

// routes
app.get('/api', (req, res) => {
    res.json({ 'Message': 'base path' })
})
// app.use('/api/docs', docs)
app.use('/api/user', userAuth_routes)

client.query("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, username VARCHAR(255) UNIQUE, email VARCHAR(255) UNIQUE, password VARCHAR NOT NULL, verified BOOLEAN DEFAULT FALSE, token VARCHAR NOT NULL DEFAULT 'Unknow')")
    .then(() => console.log('Successful connection to database'))
    .catch((e) => {
        console.error(e)
        console.log('Cannot connect to database')
    })

/* client.query('DROP TABLE users', (error, res) => {
    console.log(error, res);
    client.end()
}) */

export default app