export const userTable = "CREATE TABLE IF NOT EXISTS users(" +
    "id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
    "token VARCHAR NOT NULL DEFAULT 'Unknow',"+
    "username VARCHAR(255) UNIQUE," +
    "email VARCHAR(255) UNIQUE," +
    "password VARCHAR NOT NULL," +
    "verified BOOLEAN DEFAULT FALSE,"+
    "registry_date DATE NOT NULL DEFAULT CURRENT_DATE)"

export const pubTable = "CREATE TABLE IF NOT EXISTS publication(" +
    "userId INTEGER REFERENCES users(id),"+
    "description VARCHAR(500),"+
    "publish_date DATE NOT NULL DEFAULT CURRENT_DATE)"